export const CONSTANTS = {
  AppPages: {
    ROOTLANDING: "RootLanding",
    TAB: "Tab",
    HOME: "Home",
    PROFILE: "Profile",
    CALENDAR: "Calendar",
    CLASSES: "Classes",
    SETTINGS: "Settings",
    LOGIN: "Login",
    SIGNUP: "Signup",
    FORGOT_PASSWORD: "ForgotPassword",
    RESET_PASSWORD: "ResetPassword",
    TASKS: "Tasks",
    EXAMS: "Exams",
    SCHEDULE: "Schedule",
    COURSES: "Courses",
    COURSE: "Course",
    NOTES: "Notes",
    NOTE: "Note",
    CREATEEDITNOTE: "CreateEditNote",
    CREATECLASS:'CreateClass',
    AUTH: "Auth",
    ONBOARD: "Onboard",
  },
  STORAGE_KEYS: {
    USER: "studypal_user",
    NOTES: "studypal_notes",
  },
  CommonStyles: {
    headerRightStyle: {
      marginRight: 10,
    },
  },
  ACTION_TYPES: {
    LOGOUT_USER: "LOGOUT_USER",
    SET_USER: "SET_USER",
    EDIT_USER: "EDIT_USER",
    CREATE_NOTE: "CREATE_NOTE",
    SET_NOTES: "SET_NOTES",
    UPDATE_NOTE: "UPDATE_NOTE",
    DELETE_NOTE: "DELETE_NOTE",
  },
};
