export const CONSTANTS = {
  AppPages: {
    ROOTLANDING: "RootLanding",
    SYNCPAGE: "SyncPage",
    TAB: "Tab",
    MAINPAGES: "MainPages",
    HOME: "Home",
    PROFILE: "Profile",
    CALENDAR: "Calendar",
    CLASSES: "Classes",
    SETTINGS: "Settings",
    LOGIN: "Login",
    SIGNUP: "Signup",
    FORGOT_PASSWORD: "ForgotPassword",
    RESET_PASSWORD: "ResetPassword",
    TASKS: "Tasks",
    EXAMS: "Exams",
    SCHEDULE: "Schedule",
    COURSES: "Courses",
    COURSE: "Course",
    NOTES: "Notes",
    NOTE: "Note",
    CREATEEDITNOTE: "CreateEditNote",
    CREATEEDITCLASS: "CreateEditClass",
    CREATEEDITTASK: "CreateEditTask",
    AUTH: "Auth",
    ONBOARD: "Onboard",
  },
  STORAGE_KEYS: {
    USER: "studypal_user",
    NOTES: "studypal_notes",
    CLASSES: "studypal_classes",
    TASKS: "studypal_tasks",
  },
  CommonStyles: {
    headerRightStyle: {
      marginRight: 10,
    },
  },
  ACTION_TYPES: {
    LOGOUT_USER: "LOGOUT_USER",
    SET_USER: "SET_USER",
    EDIT_USER: "EDIT_USER",

    CREATE_NOTE: "CREATE_NOTE",
    SET_NOTES: "SET_NOTES",
    UPDATE_NOTE: "UPDATE_NOTE",
    DELETE_NOTE: "DELETE_NOTE",

    CREATE_CLASS: "CREATE_CLASS",
    SET_CLASSES: "SET_CLASSES",
    UPDATE_CLASS: "UPDATE_CLASS",
    DELETE_CLASS: "DELETE_CLASS",

    CREATE_TASK: "CREATE_TASK",
    SET_TASKS: "SET_TASKS",
    UPDATE_TASK: "UPDATE_TASK",
    DELETE_TASK: "DELETE_TASK",
  },
};
