export const CONSTANTS = {
  AppPages: {
    ROOTLANDING: "RootLanding",
    TAB: "Tab",
    HOME: "Home",
    PROFILE: "Profile",
    CALENDAR: "Calendar",
    SETTINGS: "Settings",
    LOGIN: "Login",
    SIGNUP: "Signup",
    FORGOT_PASSWORD: "ForgotPassword",
    RESET_PASSWORD: "ResetPassword",
    TASKS: "Tasks",
    EXAMS: "Exams",
    SCHEDULE: "Schedule",
    COURSES: "Courses",
    COURSE: "Course",
    NOTES: "Notes",
    NOTE: "Note",
    AUTH: "Auth",
  },
};
